# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import src.protobuf.credentials.credentials_pb2 as credentials__pb2


class CredentialsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChangeRoleUserOnAdmin = channel.unary_unary(
                '/auth.CredentialsService/ChangeRoleUserOnAdmin',
                request_serializer=credentials__pb2.ChangeRoleUser.SerializeToString,
                response_deserializer=credentials__pb2.NotificationMessage.FromString,
                )


class CredentialsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChangeRoleUserOnAdmin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CredentialsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChangeRoleUserOnAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeRoleUserOnAdmin,
                    request_deserializer=credentials__pb2.ChangeRoleUser.FromString,
                    response_serializer=credentials__pb2.NotificationMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.CredentialsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CredentialsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChangeRoleUserOnAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.CredentialsService/ChangeRoleUserOnAdmin',
            credentials__pb2.ChangeRoleUser.SerializeToString,
            credentials__pb2.NotificationMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
