# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: credentials.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63redentials.proto\x12\x04\x61uth\"&\n\x13NotificationMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"F\n\x0e\x43hangeRoleUser\x12\x13\n\x0b\x61\x64min_token\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t2^\n\x12\x43redentialsService\x12H\n\x15\x43hangeRoleUserOnAdmin\x12\x14.auth.ChangeRoleUser\x1a\x19.auth.NotificationMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'credentials_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOTIFICATIONMESSAGE']._serialized_start=27
  _globals['_NOTIFICATIONMESSAGE']._serialized_end=65
  _globals['_CHANGEROLEUSER']._serialized_start=67
  _globals['_CHANGEROLEUSER']._serialized_end=137
  _globals['_CREDENTIALSSERVICE']._serialized_start=139
  _globals['_CREDENTIALSSERVICE']._serialized_end=233
# @@protoc_insertion_point(module_scope)
