# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import src.protobuf.register.register_pb2 as register__pb2


class RegisterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterUser = channel.unary_unary(
                '/auth.RegisterService/RegisterUser',
                request_serializer=register__pb2.UserRegisterCredentials.SerializeToString,
                response_deserializer=register__pb2.NotificationRegistrMessage.FromString,
                )
        self.ActivateUser = channel.unary_unary(
                '/auth.RegisterService/ActivateUser',
                request_serializer=register__pb2.UserRegisterCredentials.SerializeToString,
                response_deserializer=register__pb2.NotificationRegistrMessage.FromString,
                )
        self.DeactivateUser = channel.unary_unary(
                '/auth.RegisterService/DeactivateUser',
                request_serializer=register__pb2.UserRegisterCredentials.SerializeToString,
                response_deserializer=register__pb2.NotificationRegistrMessage.FromString,
                )
        self.RegisterAdmin = channel.unary_unary(
                '/auth.RegisterService/RegisterAdmin',
                request_serializer=register__pb2.AdminRegisterCredentials.SerializeToString,
                response_deserializer=register__pb2.NotificationRegistrMessage.FromString,
                )


class RegisterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterUser(self, request, context):
        """пусть выдает временный токен на три дня
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateUser(self, request, context):
        """меня в БД флаг на то что юзер подтвердил почту с которой регистрировался
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeactivateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAdmin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegisterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=register__pb2.UserRegisterCredentials.FromString,
                    response_serializer=register__pb2.NotificationRegistrMessage.SerializeToString,
            ),
            'ActivateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateUser,
                    request_deserializer=register__pb2.UserRegisterCredentials.FromString,
                    response_serializer=register__pb2.NotificationRegistrMessage.SerializeToString,
            ),
            'DeactivateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeactivateUser,
                    request_deserializer=register__pb2.UserRegisterCredentials.FromString,
                    response_serializer=register__pb2.NotificationRegistrMessage.SerializeToString,
            ),
            'RegisterAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAdmin,
                    request_deserializer=register__pb2.AdminRegisterCredentials.FromString,
                    response_serializer=register__pb2.NotificationRegistrMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.RegisterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RegisterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.RegisterService/RegisterUser',
            register__pb2.UserRegisterCredentials.SerializeToString,
            register__pb2.NotificationRegistrMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ActivateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.RegisterService/ActivateUser',
            register__pb2.UserRegisterCredentials.SerializeToString,
            register__pb2.NotificationRegistrMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeactivateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.RegisterService/DeactivateUser',
            register__pb2.UserRegisterCredentials.SerializeToString,
            register__pb2.NotificationRegistrMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.RegisterService/RegisterAdmin',
            register__pb2.AdminRegisterCredentials.SerializeToString,
            register__pb2.NotificationRegistrMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
