# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AuthService.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x41uthService.proto\x12\x04\x61uth\"5\n\x0fUserCredentials\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t2J\n\x0b\x41uthService\x12;\n\rGenerateToken\x12\x15.auth.UserCredentials\x1a\x13.auth.TokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AuthService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERCREDENTIALS']._serialized_start=27
  _globals['_USERCREDENTIALS']._serialized_end=80
  _globals['_TOKENRESPONSE']._serialized_start=82
  _globals['_TOKENRESPONSE']._serialized_end=112
  _globals['_AUTHSERVICE']._serialized_start=114
  _globals['_AUTHSERVICE']._serialized_end=188
# @@protoc_insertion_point(module_scope)
